export * from "./identity";
export * from "./academy";
export * from "./people";
export * from "./operations";
export * from "./competitions";
export * from "./inventory";
export * from "./payroll";
export * from "./training";
export * from "./platform";
