export type AuthMode = "password" | "otp";

export const authConfig = {
  brand: {
    name: "Khel",
    accentWord: "Setu",
  },
  steps: [
    "Account & verification",
    "Academy profile & branding",
    "Add coaches & batches",
    "Invite your players",
  ],
  signUp: {
    activeStep: 0,
    progressPercent: 25,
    title: "Create your account",
    subtitle: "Set up your academy admin account to begin onboarding.",
    fullNameLabel: "Full name",
    fullNamePlaceholder: "Your full name",
    modes: {
      password: {
        label: "Password",
        identifierLabel: "Email or phone number",
        identifierPlaceholder: "you@academy.in or +91 98765 43210",
        passwordLabel: "Password",
        passwordPlaceholder: "Create a password",
        confirmPasswordLabel: "Confirm password",
        confirmPasswordPlaceholder: "Re-enter your password",
      },
      otp: {
        label: "OTP",
        phoneLabel: "Phone number",
        phonePlaceholder: "+91 98765 43210",
        otpLabel: "OTP",
        otpPlaceholder: "Enter 6-digit OTP",
      },
    },
    continueLabel: "Continue",
    signInPrompt: "Already have an account?",
    signInLabel: "Sign in",
  },
  login: {
    headline: ["Launch your academy's", "own digital home."],
    subcopy:
      "A fully branded web portal and mobile app for your academy — set up in four simple steps. No code, no IT team needed.",
    activeStep: 0,
    progressPercent: 25,
    title: "Sign in",
    subtitle: "Welcome back. Sign in to manage your academy or state dashboard.",
    signUpPrompt: "New to Khel Setu?",
    signUpLabel: "Create your account",
    modes: {
      password: {
        label: "Password",
        identifierLabel: "Email or phone number",
        identifierPlaceholder: "you@academy.in or +91 98765 43210",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        forgotPasswordLabel: "Forgot password?",
      },
      otp: {
        label: "OTP",
        phoneLabel: "Phone number",
        phonePlaceholder: "+91 98765 43210",
        otpLabel: "OTP",
        otpPlaceholder: "Enter 6-digit OTP",
      },
    },
    continueLabel: "Continue",
  },
  onboarding: {
    activeStep: 1,
    progressPercent: 50,
    title: "Academy profile & branding",
    subtitle:
      "This is how your players and the state dashboard will recognise you.",
    fields: {
      academyName: {
        label: "Academy name",
        defaultValue: "Dronacharya Sports Academy",
      },
      district: {
        label: "District",
        defaultValue: "Sonipat",
        suggestions: [
          "Ambala",
          "Bhiwani",
          "Charkhi Dadri",
          "Faridabad",
          "Fatehabad",
          "Gurugram",
          "Hisar",
          "Jhajjar",
          "Jind",
          "Kaithal",
          "Karnal",
          "Kurukshetra",
          "Mahendragarh",
          "Nuh",
          "Palwal",
          "Panchkula",
          "Panipat",
          "Rewari",
          "Rohtak",
          "Sirsa",
          "Sonipat",
          "Yamunanagar",
        ] as const,
      },
      brandedLink: {
        label: "Your branded link",
        defaultValue: "dronacharya",
        suffix: ".khelsetu.in",
        hint: "3–40 characters. Lowercase letters, numbers, and hyphens only. Must start and end with a letter or number.",
      },
      sports: {
        label: "Sports offered",
        defaultSports: ["Wrestling", "Boxing", "Athletics", "Kabaddi"],
        suggestions: [
          "Wrestling",
          "Boxing",
          "Athletics",
          "Kabaddi",
          "Hockey",
          "Football",
          "Cricket",
          "Judo",
          "Taekwondo",
          "Weightlifting",
          "Badminton",
          "Volleyball",
        ] as const,
        addLabel: "Add sport",
      },
      funding: {
        label: "Funding type",
        options: ["Govt-aided", "Private"] as const,
        defaultValue: "Govt-aided" as const,
      },
      brandColour: {
        label: "Brand colour",
        colors: ["#FF6B2C", "#12B886", "#2F6BFF", "#7C5CFC", "#E11D48"] as const,
        defaultValue: "#FF6B2C" as const,
      },
    },
    backLabel: "Back",
    continueLabel: "Continue",
  },
} as const;
